### ISSUE TITLE
关于最新版报错的问题

### ISSUE THREAD

**Issue by Sharkila** [chazi152/Remy_love_mod#3]
我在安装汉化组最新的软件以及汉化包后，读取存档时会出现爆红错误(不影响正常游玩)。
汉化组看了存档码文件后说可能是由于之前安装过雷米MOD导致的爆红，但是我只装汉化模组时也会爆红，想请这边看一下是否是因为雷米模组的问题？

**Comment by Sharkila** [comment]
[存档码.docx](https://github.com/chazi152/Remy_love_mod/files/14933783/default.docx)

**Comment by chazi152** [comment]
![捕获](https://github.com/chazi152/Remy_love_mod/assets/126388207/8e84d253-1766-405d-84bc-7f6f24353b7d)
不是雷米mod的问题，根据报错信息来看，是因为你原本使用的其他mod给游戏添加了9个新的npc，但是你游戏更新后导入存档码，没有那几个新NPC了，导致游戏对不上你存档码里的npc表，出现了问题

**Comment by Sharkila** [comment]
请问这种情况还有解决的办法吗orz，可能是爱机器糖果和模拟人生MOD的NPC，但是这两个MOD我试了以后并不是很喜欢所以去掉了😭没想到会突然报错



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年04月10日 23:34 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [chazi152/Remy_love_mod] 关于最新版报错的问题 (Issue #3) |

default.PNG (view on web)
不是雷米mod的问题，根据报错信息来看，是因为你原本使用的其他mod给游戏添加了9个新的npc，但是你游戏更新后导入存档码，没有那几个新NPC了，导致游戏对不上你存档码里的npc表，出现了问题

**Comment by chazi152** [comment]
https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/issues/321
你可以去看看这个链接，是我们汉化组的成员，他回答了一个一样的问题，里面有具体的解决办法

**Comment by chazi152** [comment]
刚注意到好像那个问题也是你问的，总之按照里面的步骤一步步操作就行了，用电脑打开，按f12进入浏览器的控制台，然后照着里面的一条条代码输入就行
